services:
  dev-server:
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
      target: development
    ports:
      - "8000:8000"
    restart: unless-stopped
    develop:
      watch:
        # sync the working directory with the `/app` directory in the container
        - action: sync
          path: ./packages/
          target: /app/packages/
          ignore:
            - .venv/
        # rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock
