services:
  diff_lambda:
    build:
      context: .
      dockerfile: ./docker/lambda.Dockerfile
    ports:
      - "${LAMBDA_HOST_PORT:-9000}:8080"
    volumes:
      - ./packages/core/src/core:/var/task/core:ro
      - ./packages/diff_lambda/src/diff_lambda:/var/task/app:ro
    environment:
      - VERSION=local
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      - localstack
    restart: unless-stopped
    develop:
      watch:
        # restart lambda to reload changes from the mounted source packages
        - action: restart
          path: ./packages/core/src/core
        - action: restart
          path: ./packages/diff_lambda/src/diff_lambda
        # rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock

  localstack:
    # image: docker.io/localstack/localstack:community-archive
    image: docker.io/floci/floci:latest-compat
    ports:
      - "${LOCALSTACK_HOST_PORT:-4566}:4566"
    environment:
      - SERVICES=s3,dynamodb,sqs
      - PERSISTENCE=1
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
    volumes:
      # - localstack-data:/var/lib/localstack
      - localstack-data:/app/data
      # - ./docker/s3-init.sh:/etc/localstack/init/ready.d/10-s3-init.sh
      - ./docker/localstack-init.py:/etc/localstack/init/ready.d/10-localstack-init.py
      # - ./docker/dynamodb-init.sh:/etc/localstack/init/ready.d/20-dynamodb-init.sh
      # - /var/run/docker.sock:/var/run/docker.sock

  queue-poller:
    image: ghcr.io/astral-sh/uv:0.11-python3.14-alpine
    command: uv run /app/local-sqs-poller.py
    volumes:
      - ./docker/local-sqs-poller.py:/app/local-sqs-poller.py:ro
      - queue-poller-cache:/root/.cache/uv
    environment:
      - UV_CACHE_DIR=/root/.cache/uv
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - QUEUE_URL=http://localstack:4566/000000000000/did-eicr-events
      - LAMBDA_URL=http://diff_lambda:8080/2015-03-31/functions/function/invocations
    depends_on:
      - localstack
      - diff_lambda
    restart: unless-stopped

volumes:
  localstack-data:
  queue-poller-cache:
